modLoader="javafml"
loaderVersion="${fml_version_range}"
issueTrackerURL="https://gitlab.com/CDAGaming/CraftPresence/issues"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/CDAGaming/VersionLibrary/master/CraftPresence/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/craftpresence"
logoFile="logo.png"
credits=""
authors="CDAGaming"
description='''
Completely Customize the way others see you play in Discord!
'''

[[dependencies.${mod_id}]]
    modId="${forge_id}"
    mandatory=true
    versionRange="${loader_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="unilib"
    mandatory=true
    versionRange="[${unilib_min_version},]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${game_version_range}"
    ordering="NONE"
    side="BOTH"