name: Build

on:
  push:
    branches-ignore:
      - l10n_master
  workflow_dispatch:
    inputs:
      release_all:
        description: 'Deploy All'
        required: true
        default: false
        type: boolean
      release_curseforge:
        description: 'Deploy CurseForge'
        required: true
        default: false
        type: boolean
      release_modrinth:
        description: 'Deploy Modrinth'
        required: true
        default: false
        type: boolean
      release_nightbloom:
        description: 'Deploy NightBloom'
        required: true
        default: false
        type: boolean

env:
  CF_APIKEY: ${{ secrets.CF_APIKEY }}
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  NIGHTBLOOM_TOKEN: ${{ secrets.NIGHTBLOOM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: update cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/unimined
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Gradle JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew --build-cache --info --stacktrace build

      - name: Deploy to CurseForge
        if: |
          github.event.inputs.release_all || github.event.inputs.release_curseforge
        run: ./gradlew --build-cache --info --stacktrace publishCurseforge

      - name: Deploy to Modrinth
        if: |
          github.event.inputs.release_all || github.event.inputs.release_modrinth
        run: ./gradlew --build-cache --info --stacktrace publishModrinth

      - name: Deploy to NightBloom
        if: |
          github.event.inputs.release_all || github.event.inputs.release_nightbloom
        run: ./gradlew --build-cache --info --stacktrace publishNightbloom

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            **/build/libs/
            !buildSrc/build/libs/
            !build/libs/
            !**/*-dev.jar
            !**/*-shadow.jar
            !**/*-transformProduction*.jar
            !**/testmod*/

      - name: stop daemon
        run: ./gradlew --stop