name: Deploy Curseforge

on: workflow_dispatch

env:
  CF_APIKEY: ${{ secrets.CF_APIKEY }}
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew --build-cache --info --stacktrace build

      - name: Merge Jars with Gradle
        run: ./gradlew --build-cache --info --stacktrace mergeJars

      - name: Deploy with Gradle
        run: ./gradlew --build-cache --info --stacktrace :common:publishCurseforge

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: build/libs/*.jar

      - name: stop daemon
        run: ./gradlew --stop